### ISSUE TITLE
Error installing via gem(remote repo)

### ISSUE THREAD

**Issue by hahwul** [hahwul/XSpear#2]
from @xaeroborg
Hi hahwul, is this issue regarding the rake or something else. Also I have cloned the git repository as well. But I just tried installing via gem

<img width="554" alt="1414" src="https://user-images.githubusercontent.com/13212227/61580899-0de09200-ab52-11e9-9410-5ef15a6f4f56.png">

**Comment by hahwul** [comment]
My develop set
```
+ ruby: 2.4.6
+ gem: 3.0.3
```

```
$ rvm list
   ruby-2.3.7 [ x86_64 ]
=* ruby-2.4.6 [ x86_64 ]

$ gem -v 
3.0.3
```

**Comment by xaeroborg** [comment]
Mine,
gem --version = 2.5.2.2
ruby --version = ruby 2.3.6p384 (2017-12-14) [x86_64-linux-gnu]

**Comment by xaeroborg** [comment]
Its the same error. By the way my version number doesnt match yours. Is that the issue?
![image](https://user-images.githubusercontent.com/33274680/61581422-2b106300-ab48-11e9-9c6c-bb0efaee7a14.png)

**Comment by hahwul** [comment]
@xaeroborg 
I do not know yet :)
first of all, I wrote it for reference first. I think should test it in the same environment of error (kali).

**Comment by xaeroborg** [comment]
Yes I believe its looking for a "PATH" thats not available in Kali. I think thats why. Anyways I will wait for your update. Thanks @hahwul

**Comment by hahwul** [comment]
@xaeroborg 
Yes, I will find the cause and update it.
I have one question, please check it when it is time.

Is there an error when I try to install the gems below?

```
$ gem install selenium-webdriver
```

It seems to be a problem during installation of the dependency gem. 
This issue seems to be somewhat similar.

https://stackoverflow.com/questions/56566599/unable-to-install-ruby-gem-selenium-webdriver-on-ubuntu-19-04

**Comment by xaeroborg** [comment]
Oh yes I forgot to tell you. I did try installing the dependencies individually and I did get a an error as the following
![image](https://user-images.githubusercontent.com/33274680/61582203-d540b880-ab51-11e9-8e9d-c7a47cbe6f4e.png)

**Comment by xaeroborg** [comment]
Update: Your fix found in stackoverflow worked like a charm
![image](https://user-images.githubusercontent.com/33274680/61582239-57c97800-ab52-11e9-9f1c-d6867a778b8a.png)
Worked!
![image](https://user-images.githubusercontent.com/33274680/61582244-66b02a80-ab52-11e9-80c0-4e53bfbf8e6e.png)

**Comment by hahwul** [comment]
@xaeroborg 
It's a good thing. thank you for everything!
