### ISSUE TITLE
HEY what is function of --raw=FILENAME 

### ISSUE THREAD

**Issue by Machineyadav** [hahwul/XSpear#29]
It has been given that it loads file.The file is loaded for what. Is it the post data file we captured from burp to find xss or is it the file that loads xss payloads for testing xss. if there is no such feature then add a feature which loads payload from a file and use it for xss testing

**Comment by hahwul** [comment]
@Machineyadav 
Hi. 
I made it to load raw request captured in the burp suite. But there's still a lot of bugs.
Usually this type of request will be included.
```
GET /test.do HTTP/1.1
Host: 127.0.0.1
blahblah~
```
