### ISSUE TITLE
xss in path

### ISSUE THREAD

**Issue by ghsec** [hahwul/XSpear#36]
Sometimes need check xss in path.

**Comment by hahwul** [comment]
Hi @ghsec , 
Thank you for a good idea. I am of the same opinion. 
I'm thinking of an option to specify a inject point to test, but if you have anything to add, please let me know.

```
- params
- cookie
- path
- user-agent
```

Cookie and UA are thinking about integrating into the header. But Heather may have the potential to induce malfunctions..

**Comment by ghsec** [comment]
And need add xss oauloads in js functio

**Comment by ghsec** [comment]
I will try edit and test this localy.

**Comment by hahwul** [comment]
However, I will develop the path(and js function) testing first. it as need some structural changes to support all the inject points. I'll leave a comment when I'm done. 

I always welcome pull requests :)

**Comment by ghsec** [comment]
Ok thank

**Comment by hahwul** [comment]
Hi @ghsec ,
As I was thinking about plan, I have a question. Is it true that what you said was the addition of an XSS case that works inside the JS? Let me know if I got it wrong!

e.g
```javascript
// [test param on request ]: '+alert(45);//
// [ response ]

var a = 'test'+alert(45);//';

```

**Comment by hahwul** [comment]
If the above content is correct, I think it would be better to add payload, and Selenium detection would be less misleading than Reflected detection. (It was just memo for me)

**Comment by ghsec** [comment]
@hahwul sorry I don't know python but it is right way, keyword'-alert(45)-'
keyword for search reflection and you can build regexs for detecting xss payloads.

**Comment by ghsec** [comment]
@hahwul we can change ideas on twitter
[@GochaOqradze] (https://twitter.com/GochaOqradze)

**Comment by hahwul** [comment]
@ghsec 
I understood it. I also knew the need to add these skill(in-js) because they are used a lot. Thank you for your opinion! Maybe next January at the latest, v1.3 with that feature will be released! Thank you very much.

**Comment by hahwul** [comment]
Hi @ghsec ,
Version 1.3 with path scan and in-js scan is released. Maybe i need to add more patterns. If you need a bug or a pattern, please leave a comment. Thank you very much for your good opinion. Happy New Year
```
$ gem update XSpear
```
