### ISSUE TITLE
XSpear computer hanged.

### ISSUE THREAD

**Issue by jepunband** [hahwul/XSpear#46]
so i ran this command :
xspear -u "http://testphp.vulnweb.com/listproducts.php?cat=123" -v 1

my pc slowed down and finally hanged!

**Comment by hahwul** [comment]
Hi @jepunband 
Thank you for reporting,
Xspear also uses the selenium drive, which consumes a lot of resources. 

First, I think we should adjust the thread(default 10) to the minimum.
```
$ xspear -u "http://testphp.vulnweb.com/listproducts.php?cat=123" -v 1 -t 1
```

If it's an issue not a performance issue, but an issue at a specific option, please tell me.
