### ISSUE TITLE
ruby warnings 

### ISSUE THREAD

**Issue by Th3F0x-code** [hahwul/XSpear#47]
every time you run the program, ruby starts recording several warnings

**https://pastebin.com/raw/Gx0aQwNi**

**Comment by hahwul** [comment]
Hi! Thank you for issue.
It's an issue I'm aware of and I'll try to correct it. Thank you.

Same Issue : https://github.com/hahwul/XSpear/issues/45

**Comment by hahwul** [comment]
@Th3F0x-code 
Updated XSpear 1.3.2! 
```
$ gem update XSpear
```
